// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSkDA-Ozr3qs__sJlSLCSg0Y0QCL4wfAU',
    appId: '1:389789106640:web:4d23fa974bf8e6995579d5',
    messagingSenderId: '389789106640',
    projectId: 'archgod-71172',
    authDomain: 'archgod-71172.firebaseapp.com',
    storageBucket: 'archgod-71172.firebasestorage.app',
    measurementId: 'G-H91F5BM2YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM5W9kcfKRHKDWBVWlUf6yYuZUhOBXVLw',
    appId: '1:389789106640:android:3b69f6fd480c349c5579d5',
    messagingSenderId: '389789106640',
    projectId: 'archgod-71172',
    storageBucket: 'archgod-71172.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1FA7HUsOp68xsI5HjzZRgXeCQymYqplI',
    appId: '1:389789106640:ios:560921b1c923ca1f5579d5',
    messagingSenderId: '389789106640',
    projectId: 'archgod-71172',
    storageBucket: 'archgod-71172.firebasestorage.app',
    iosBundleId: 'com.example.productreward',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1FA7HUsOp68xsI5HjzZRgXeCQymYqplI',
    appId: '1:389789106640:ios:3ae393d6acdde03b5579d5',
    messagingSenderId: '389789106640',
    projectId: 'archgod-71172',
    storageBucket: 'archgod-71172.firebasestorage.app',
    iosBundleId: 'com.app.productreward',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSkDA-Ozr3qs__sJlSLCSg0Y0QCL4wfAU',
    appId: '1:389789106640:web:25fe068f51a514365579d5',
    messagingSenderId: '389789106640',
    projectId: 'archgod-71172',
    authDomain: 'archgod-71172.firebaseapp.com',
    storageBucket: 'archgod-71172.firebasestorage.app',
    measurementId: 'G-ZE3WEZHHG3',
  );
}
